version: '2.6'
services:
  my-tf-container:
    image: my-tf:1.3
    ports:
      # Open port for Jupyter notebook
      - 8888:8888
      # Open port for TensorBoard
      - 6006:6006
    # Connects all GPU's on Host to the Container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
